config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

import backyard

from website.views import bad_request, server_error

urlpatterns = [
    # Languages
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Django Admin
    url(settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^backend/', include(backyard.get_urls(), namespace='backyard')),
    url(r'', include('fundraising.urls', namespace='fundraising')),

    # url(r'', include('fundraising.modules.store_commerce.urls', namespace='store_commerce')),

    url(r'', include('website.common.urls', namespace='common')),
    url(r'', include('website.pages.urls', namespace='pages')),
    url(r'', include('website.donations.urls', namespace='donations')),

    url(r'^summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'website.views.bad_request'
handler500 = 'website.views.server_error'

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', bad_request),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', server_error),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

website/common/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^form/csrf/$', view=views.get_form_csrf, name='form_csrf'),
]

website/donation/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^listing/$', view=views.listing, name='listing'),
    url(r'^product/(?P<product_id>\d+)/$', view=views.product_view, name='product_view'),

    url(r'^cart/$', view=views.cart_view, name='cart_view'),

    url(r'^checkout/$', view=views.checkout, name='checkout'),
    url(r'^checkout/payment/$', view=views.checkout_payment, name='checkout_payment'),

    url(r'^order/(?P<order_number>\w+)/$', view=views.order_details, name='order_details'),

]

website/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', view=views.homepage, name='homepage'),

]

backyard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models


# TODO : Add user's role model

"""
class BackyardUserRoleName(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)


class BackyardUserRole(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='backyard_role')
    role = models.ForeignKey('BackyardUserRoleName')
"""

website/donation/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

backyard/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms


#class ListViewSearchForm(forms.Form):
#    from_date = forms.DateField(required=False, input_formats=['%d/%m/%Y'], widget=forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control'}))
#    to_date = forms.DateField(required=False, input_formats=['%d/%m/%Y'], widget=forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control'}))
#    keyword = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))


class ListViewSearchForm(forms.Form):
    keyword = forms.CharField(max_length=500, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

website/backyard/forms/donations.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from fundraising.modules.fund_donation.enums import DonationPaymentStatus


class ConfirmaedDonationsSearchForm(forms.Form):
    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))


class IncompleteDonationsSearchForm(forms.Form):
    PAYMENT_STATUS_CHOICES = (
        (DonationPaymentStatus.OFFLINE_PAYMENT_WAITING, DonationPaymentStatus.OFFLINE_PAYMENT_WAITING_TEXT),
        (DonationPaymentStatus.OFFLINE_PAYMENT_DECLINED, DonationPaymentStatus.OFFLINE_PAYMENT_DECLINED_TEXT),
        (DonationPaymentStatus.PAYMENT_FAILED, DonationPaymentStatus.PAYMENT_FAILED_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_STAFF, DonationPaymentStatus.RECURRING_STOPPED_BY_STAFF_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_SYSTEM, DonationPaymentStatus.RECURRING_STOPPED_BY_SYSTEM_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_USER, DonationPaymentStatus.RECURRING_STOPPED_BY_USER_TEXT),
    )

    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    payment_status = forms.MultipleChoiceField(choices=PAYMENT_STATUS_CHOICES, widget=forms.SelectMultiple(attrs={'class': 'form-control'}), required=False)


class AllDonationsSearchForm(forms.Form):
    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    payment_status = forms.MultipleChoiceField(choices=DonationPaymentStatus.DATA_CHOICES, widget=forms.SelectMultiple(attrs={'class': 'form-control'}), required=False)

website/donation/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.core import validators

from fundraising.constants import TH_PROVINCE_CHOICES
from fundraising.modules.store_commerce.models import Cart

"""
class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(validators=[validators.MinValueValidator(1)])

    def save(self, request, product):
        cart = Cart.objects.get_or_create_from_request(request)
        quantity = self.cleaned_data['quantity']
        return cart.add_product_to_cart(product, quantity)
"""


class CheckoutForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    # Address
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    province = forms.ChoiceField(choices=TH_PROVINCE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    zip_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def save(self, cart):
        cart.update_shopper(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            email=self.cleaned_data['email']
        )

        fullname = '{} {}'.format(self.cleaned_data['first_name'], self.cleaned_data['last_name'])

        cart.update_shipping_address(
            fullname=fullname,
            address=self.cleaned_data['address'],
            city=self.cleaned_data['city'],
            province=self.cleaned_data['province'],
            country='TH',
            zip_code=self.cleaned_data['zip_code'],
            phone_number=self.cleaned_data['phone_number'],
        )

        cart.update_billing_address(
            fullname=fullname,
            address=self.cleaned_data['address'],
            city=self.cleaned_data['city'],
            province=self.cleaned_data['province'],
            country='TH',
            zip_code=self.cleaned_data['zip_code'],
            phone_number=self.cleaned_data['phone_number'],
        )

        return cart


class CheckoutPaymentForm(forms.Form):
    pass

website/common/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.middleware import csrf
from django.views.decorators.cache import never_cache


@never_cache
def get_form_csrf(request):
    token = csrf.get_token(request)

    return HttpResponse(token)

website/donation/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from fundraising.modules.store_commerce.functions import get_functions as commerce_fn
from fundraising.modules.store_commerce.models import Product, Cart, Order

from .forms import CheckoutForm


def listing(request):
    products = Product.objects.published()

    return render(request, 'pages/listing.html', {
        'products': products,
    })


def product_view(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if not product.is_published:
        raise Http404

    return render(request, 'pages/product_page.html', {
        'product': product,
    })


def cart_view(request):
    cart = Cart.objects.get_from_request(request)
    cart.update()

    return render(request, 'pages/cart.html', {

    })


def checkout(request):
    cart = Cart.objects.get_from_request(request)

    if not cart or cart.is_empty:
        return redirect('commerce:cart_view')

    if request.method == 'POST':
        checkout_form = CheckoutForm(request.POST)

        if checkout_form.is_valid():
            checkout_form.save(cart)
            return redirect('commerce:checkout_payment')

    else:
        initial = {}
        if cart.shopper:
            shopper = cart.shopper
            initial.update({
                'first_name': shopper.first_name,
                'last_name': shopper.last_name,
                'email': shopper.email,
            })

        if cart.shipping_address:
            shipping_address = cart.shipping_address
            initial.update({
                'phone_number': shipping_address.phone_number,
                'address': shipping_address.address,
                'city': shipping_address.city,
                'province': shipping_address.province,
                'zip_code': shipping_address.zip_code,
            })

        checkout_form = CheckoutForm(initial=initial)

    return render(request, 'commerce/checkout.html', {
        'checkout_form': checkout_form,
    })


def checkout_payment(request):
    cart = Cart.objects.get_from_request(request)

    if request.method == 'POST':
        order = commerce_fn.checkout(cart)

        if order.total == 0:
            order.set_no_payment_required()

        else:

            # DUMMY : Assume payment is collected right away
            order.set_payment_paid()

            # request.session[''] = ''  # TODO : Add success message after purchase

        order.save()

        commerce_fn.unlink_cart(request)

        # TODO : Clear cart

        return redirect('commerce:order_details', order_number=order.order_number)

    return render(request, 'commerce/checkout_payment.html', {})


def order_details(request, order_number):
    order = Order.objects.get(order_number=order_number)

    return render(request, 'commerce/order_details.html', {
        'order': order,
    })

website/pages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from fundraising.modules.fund_donation.models import DonationCampaign


def homepage(request):
    campaigns = DonationCampaign.objects.ongoing_campaigns()

    return render(request, 'pages/homepage.html', {
        'campaigns': campaigns,
    })

website/views.py
from django.shortcuts import render


def bad_request(request):
    response = render(request, '400.html')
    response.status_code = 400
    return response


def server_error(request):
    response = render(request, '500.html')
    response.status_code = 500
    return response

website/templates/backyard/donations/donations_all.html
{% extends 'backyard/base.html' %}
{% load i18n common backyard donations %}

{% block body_css_class %}backyard-donations{% endblock %}

{% block content %}
    {% include 'backyard/donations/includes/donations_tabs.html' %}

    <div class="searchbar">
        <form method="get" action=".">
            <div class="clearfix">
                <div class="pull-left">
                    <div class="form-group filter-keyword">
                        <label for="id_keyword" class="form-label">Keyword</label><br/>
                        {{ search_form.keyword }}
                    </div>

                    <div class="form-group filter-daterange has-feedback">
                        <label for="id_filter_donation_date" class="form-label">Donation date</label><br/>
                        {{ search_form.date_submitted_range }}
                        <span class="fa fa-calendar form-control-feedback" aria-hidden="true"></span>
                    </div>
                    <div class="form-group filter-status">
                        <label for="id_payment_status" class="form-label">Payment status</label><br/>
                        {{ search_form.payment_status }}
                    </div>
                </div>

                <div class="pull-right">
                    <div class="submit-buttons">
                        <button class="btn button-submit" type="submit"><i class="fa fa-search"></i> Search</button>
                        <button class="btn button-reset" type="button" id="searchbar_reset_button">Reset</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="number-of-results">
        Found <span class="number">{{ page_obj.paginator.count }}</span> donations
    </div>

    <div class="cardbox cardbox-table">
        {% if not search_form.is_empty %}
        <div class="table-filtering">
            {% if search_form_values.keyword %}
                <span class="criteria"><span class="name">Keyword</span> <span class="value">{{ search_form_values.keyword }}</span></span>
            {% endif %}

            {% if search_form_values.date_submitted_range %}
                <span class="criteria"><span class="name">Donation date</span> <span class="value">{{ search_form_values.date_submitted_range }}</span></span>
            {% endif %}

            {% if search_form_values.payment_status %}
                {% for status in search_form_values.payment_status %}
                    <span class="criteria"><span class="name">Payment status</span> <span class="value">{{ status|payment_status_text }}</span></span>
                {% endfor %}
            {% endif %}
        </div>
        {% endif %}

        {% if object_list %}
        <div class="table-header">
            <div class="row">
                <div class="col-md-6">
                    <div class="table-actions">
                        <div class="dropdown">
                            <button class="btn button-gray -small dropdown-toggle" type="button" id="table-export-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Export <i class="fa fa-caret-down"></i></button>
                            <ul class="dropdown-menu" aria-labelledby="table-export-button">
                                <li><a href="#">Export to Excel</a></li>
                                <li><a href="#">Export to CSV</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="table-pagination">
                        <nav aria-label="Page navigation">
                            <div class="current"><span class="number">{{ page_obj.start_index }}</span>-<span class="number">{{ page_obj.end_index }}</span> of <span class="number">{{ page_obj.paginator.count }}</span></div>
                            <ul class="pagination">
                                <li{% if not page_obj.has_previous %} class="disabled"{% endif %}><a href="#" aria-label="Previous"><i class="fa fa-chevron-left"></i></a></li>
                                <li{% if not page_obj.has_next %} class="disabled"{% endif %}><a href="#" aria-label="Next"><i class="fa fa-chevron-right"></i></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        {% if object_list %}
            <table class="table table-default table-donations">
                <thead>
                    <tr>
                        <th class="datetime">{% trans 'Donation date' %}</th>
                        <th class="name_email">{% trans 'Donor name' %}</th>
                        <th class="amount">{% trans 'Amount' %}</th>
                        <th class="campaign">{% trans 'Campaign' %}</th>
                        <th class="payment">{% trans 'Payment' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for donation in object_list %}
                        <tr class="clickable-row">
                            <td class="datetime">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_datetime donation.date_submitted %}
                                </a>
                            </td>
                            <td class="name_email">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_name_email donation.donor_fullname donation.donor_email %}
                                </a>
                            </td>
                            <td class="amount">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_donation_amount donation %}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_donation_campaign donation %}
                                </a>
                            </td>
                            <td class="payment status">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_donation_payment donation %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="table-footer">
                <div class="table-pagination">
                    <nav aria-label="Page navigation">
                        <div class="current"><span class="number">{{ page_obj.start_index }}</span>-<span class="number">{{ page_obj.end_index }}</span> of <span class="number">{{ page_obj.paginator.count }}</span></div>
                        <ul class="pagination">
                            <li{% if not page_obj.has_previous %} class="disabled"{% endif %}><a href="#" aria-label="Previous"><i class="fa fa-chevron-left"></i></a></li>
                            <li{% if not page_obj.has_next %} class="disabled"{% endif %}><a href="#" aria-label="Next"><i class="fa fa-chevron-right"></i></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        {% else %}
            <div class="table-no-objects">No donations found</div>
        {% endif %}

    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">

$(function() {
    $('#id_date_submitted_range').daterangepicker({
        autoUpdateInput: false,
        locale: {
            format: 'DD-MM-YYYY',
            cancelLabel: 'Reset'
        }
    }).on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
    }).on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
    });

    $('#id_payment_status').multiselect({
        nonSelectedText: 'Any status',
        allSelectedText: 'All status'
    });

    $('#searchbar_reset_button').on('click', function() {
        window.location = '{{ request.path }}';
    });


});
</script>
{% endblock %}

website/templates/backyard/donations/donations_incomplete.html
{% extends 'backyard/base.html' %}
{% load i18n common backyard donations %}

{% block body_css_class %}backyard-donations{% endblock %}

{% block content %}
    {% include 'backyard/donations/includes/donations_tabs.html' %}

    <div class="searchbar">
        <form method="get" action=".">
            <div class="clearfix">
                <div class="pull-left">
                    <div class="form-group filter-keyword">
                        <label for="id_keyword" class="form-label">Keyword</label><br/>
                        {{ search_form.keyword }}
                    </div>

                    <div class="form-group filter-daterange has-feedback">
                        <label for="id_filter_donation_date" class="form-label">Donation date</label><br/>
                        {{ search_form.date_submitted_range }}
                        <span class="fa fa-calendar form-control-feedback" aria-hidden="true"></span>
                    </div>
                    <div class="form-group filter-status">
                        <label for="id_payment_status" class="form-label">Payment status</label><br/>
                        {{ search_form.payment_status }}
                    </div>
                </div>

                <div class="pull-right">
                    <div class="submit-buttons">
                        <button class="btn button-submit" type="submit"><i class="fa fa-search"></i> Search</button>
                        <button class="btn button-reset" type="button" id="searchbar_reset_button">Reset</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="number-of-results">
        Found <span class="number">{{ page_obj.paginator.count }}</span> donations
    </div>

    <div class="cardbox cardbox-table">
        {% if not search_form.is_empty %}
        <div class="table-filtering">
            {% if search_form_values.keyword %}
                <span class="criteria"><span class="name">Keyword</span> <span class="value">{{ search_form_values.keyword }}</span></span>
            {% endif %}

            {% if search_form_values.date_submitted_range %}
                <span class="criteria"><span class="name">Donation date</span> <span class="value">{{ search_form_values.date_submitted_range }}</span></span>
            {% endif %}

            {% if search_form_values.payment_status %}
                {% for status in search_form_values.payment_status %}
                    <span class="criteria"><span class="name">Payment status</span> <span class="value">{{ status|payment_status_text }}</span></span>
                {% endfor %}
            {% endif %}
        </div>
        {% endif %}

        {% if object_list %}
        <div class="table-header">
            <div class="row">
                <div class="col-md-6">
                    <div class="table-actions">
                        <div class="dropdown">
                            <button class="btn button-gray -small dropdown-toggle" type="button" id="table-export-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Export <i class="fa fa-caret-down"></i></button>
                            <ul class="dropdown-menu" aria-labelledby="table-export-button">
                                <li><a href="#">Export to Excel</a></li>
                                <li><a href="#">Export to CSV</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="table-pagination">
                        <nav aria-label="Page navigation">
                            <div class="current"><span class="number">{{ page_obj.start_index }}</span>-<span class="number">{{ page_obj.end_index }}</span> of <span class="number">{{ page_obj.paginator.count }}</span></div>
                            <ul class="pagination">
                                <li{% if not page_obj.has_previous %} class="disabled"{% endif %}><a href="#" aria-label="Previous"><i class="fa fa-chevron-left"></i></a></li>
                                <li{% if not page_obj.has_next %} class="disabled"{% endif %}><a href="#" aria-label="Next"><i class="fa fa-chevron-right"></i></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        {% if object_list %}
            <table class="table table-default table-donations">
                <thead>
                    <tr>
                        <th class="datetime">{% trans 'Donation date' %}</th>
                        <th class="name_email">{% trans 'Donor name' %}</th>
                        <th class="amount">{% trans 'Amount' %}</th>
                        <th class="payment">{% trans 'Payment' %}</th>
                        <th class="reason">{% trans 'Reason' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for donation in object_list %}
                        <tr class="clickable-row">
                            <td class="datetime">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_datetime donation.date_submitted %}
                                </a>
                            </td>
                            <td class="name_email">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_name_email donation.donor_fullname donation.donor_email %}
                                </a>
                            </td>
                            <td class="amount">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_donation_amount donation %}
                                </a>
                            </td>
                            <td class="payment status">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_donation_payment donation %}
                                </a>
                            </td>
                            <td class="reason">
                                <a href="{% url 'backyard:donation_page' number=donation.donation_number %}">
                                    {% display_donation_fail_reason donation %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="table-footer">
                <div class="table-pagination">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <li{% if not page_obj.has_previous %} class="disabled"{% endif %}><a href="#" aria-label="Previous"><i class="fa fa-caret-left"></i> Previous</a></li>
                            <li class="current">{{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }}</li>
                            <li{% if not page_obj.has_next %} class="disabled"{% endif %}><a href="#" aria-label="Next">Next <i class="fa fa-caret-right"></i></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        {% else %}
            <div class="table-no-objects">No matching donations found</div>
        {% endif %}

    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">

$(function() {
    $('#id_date_submitted_range').daterangepicker({
        autoUpdateInput: false,
        locale: {
            format: 'DD-MM-YYYY',
            cancelLabel: 'Reset'
        }
    }).on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
    }).on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
    });

    $('#id_payment_status').multiselect({
        nonSelectedText: 'Any status',
        allSelectedText: 'All status',
        numberDisplayed: 1

    });

    $('#searchbar_reset_button').on('click', function() {
        window.location = '{{ request.path }}';
    });


});
</script>
{% endblock %}