config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

import backyard

from website.views import bad_request, server_error

urlpatterns = [
    # Languages
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Django Admin
    url(settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^backend/', include(backyard.get_urls(), namespace='backyard')),
    url(r'', include('fundraising.urls', namespace='fundraising')),

    # url(r'', include('fundraising.modules.store_commerce.urls', namespace='store_commerce')),

    url(r'', include('website.common.urls', namespace='common')),
    url(r'', include('website.pages.urls', namespace='pages')),
    url(r'', include('website.donations.urls', namespace='donations')),

    url(r'^summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'website.views.bad_request'
handler500 = 'website.views.server_error'

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', bad_request),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', server_error),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

website/common/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^form/csrf/$', view=views.get_form_csrf, name='form_csrf'),
]

website/donation/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^listing/$', view=views.listing, name='listing'),
    url(r'^product/(?P<product_id>\d+)/$', view=views.product_view, name='product_view'),

    url(r'^cart/$', view=views.cart_view, name='cart_view'),

    url(r'^checkout/$', view=views.checkout, name='checkout'),
    url(r'^checkout/payment/$', view=views.checkout_payment, name='checkout_payment'),

    url(r'^order/(?P<order_number>\w+)/$', view=views.order_details, name='order_details'),

]

website/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', view=views.homepage, name='homepage'),

]

fundraising/modules/fund_donation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils import timezone

from autoslug import AutoSlugField
from easy_thumbnails.fields import ThumbnailerImageField
from model_utils.models import TimeStampedModel
from django_fsm import FSMField, transition

from fundraising import app_settings as store_app_settings
from fundraising import constants
from fundraising.enums import TransactionActionStatus
from fundraising.modules.fund_donation import app_settings as donation_app_settings
from fundraising.models import Person, decimalfield_kwargs, ChargeableMixin, RecurringInstructionMixin, \
    AbstractRecurringInstruction, AbstractRecurringSequence
from fundraising.utils.common import split_filepath
from fundraising.utils.interval import extract_interval, display_interval
from fundraising.validators import validate_file_max_size

from . import signals
from .enums import DonationCampaignStatus, DonationStatus, DonationType, \
    DonationPaymentStatus, DonationRecurringSequenceStatus


class Donor(Person):
    class Meta:
        proxy = True

    def do_something(self):
        pass


# DONATION CAMPAIGN ####################################################################################################

class DonationCampaignCategory(models.Model):
    slug = AutoSlugField(populate_from='name', max_length=300, blank=True, editable=True)
    name = models.CharField(max_length=100)
    sorting_order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['sorting_order']

    def __unicode__(self):
        return self.name


def get_campaign_cover_image_dir(instance, filename):
    (head, name, ext) = split_filepath(filename)
    timestamp = timezone.now().strftime('%Y%m%d-%H%M%S')
    return 'campaigns/{0}/cover-{1}.{2}'.format(instance.id, timestamp, ext)


def get_campaign_fb_share_image_dir(instance, filename):
    (head, name, ext) = split_filepath(filename)
    timestamp = timezone.now().strftime('%Y%m%d-%H%M%S')
    return 'campaigns/{0}/share-fb-{1}.{2}'.format(instance.id, timestamp, ext)


class DonationCampaignQuerySet(models.QuerySet):

    def ongoing_campaigns(self):
        return self.filter(status=DonationCampaignStatus.ONGOING)

    def closed_campaigns(self):
        return self.filter(status=DonationCampaignStatus.CLOSED)


class DonationCampaignManager(models.Manager):
    def get_queryset(self):
        return DonationCampaignQuerySet(self.model, using=self._db)

    def ongoing_campaigns(self):
        return self.get_queryset().ongoing_campaigns()

    def closed_campaigns(self):
        return self.get_queryset().closed_campaigns()


class DonationCampaign(TimeStampedModel):
    slug = AutoSlugField(populate_from='name', max_length=300, blank=True, editable=True)
    name = models.CharField(max_length=300)
    teaser = models.TextField(blank=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey('DonationCampaignCategory', null=True, blank=True, related_name='campaigns')
    status = FSMField(default=DonationCampaignStatus.DRAFT, choices=DonationCampaignStatus.DATA_CHOICES)
    cover_image = ThumbnailerImageField(null=True, blank=True,
                                        upload_to=get_campaign_cover_image_dir,
                                        resize_source=donation_app_settings.THUMBNAIL_SAVE_ORIGINAL['campaign_cover'],
                                        validators=[validate_file_max_size, ])

    objects = DonationCampaignManager()

    def __unicode__(self):
        return '{name} (status: {status})'.format(
            name=self.name,
            status=DonationCampaignStatus.DATA_MAP[self.status]['text'])

    @property
    def status__display(self):
        return DonationCampaignStatus.DATA_MAP[self.status]['text']

    def get_absolute_url(self):
        if self.slug:
            return reverse('donations:donate_campaign_with_slug', args=(self.slug, ))
        else:
            return reverse('donations:donate_campaign', args=(self.id, ))

    @property
    def is_public(self):
        # Note: If closed campaign can still be viewed by website user, add condition below to include 'CLOSED'
        return self.status == DonationCampaignStatus.ONGOING

    @property
    def is_able_to_donate(self):
        return self.status == DonationCampaignStatus.ONGOING


class DonationCampaignAmount(models.Model):
    campaign = models.ForeignKey('DonationCampaign', related_name='amount_choices', null=True, blank=True)
    amount = models.DecimalField(validators=[MinValueValidator(donation_app_settings.MINIMUM_DONATION_AMOUNT)],
                                 **decimalfield_kwargs)
    description = models.CharField(max_length=512, blank=True, null=True, default='')
    sorting_order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ('sorting_order', )


# DONATION #############################################################################################################

def generate_donation_number():
    from django.db import transaction
    from sequences import get_next_value

    with transaction.atomic():
        format_str = '{{:0{0}}}'.format(donation_app_settings.DONATION_NUMBER_LENGTH)
        next_number = get_next_value('donations')
        return format_str.format(next_number)


class DonationQuerySet(models.QuerySet):

    def confirmed_donations(self):
        return self.filter(is_confirmed=True)


class DonationManager(models.Manager):
    def get_queryset(self):
        return DonationQuerySet(self.model, using=self._db)

    def confirmed_donations(self):
        return self.get_queryset().confirmed_donations()


class Donation(ChargeableMixin, TimeStampedModel):
    person = models.ForeignKey('fundraising.Person', related_name='donations')

    donation_number = models.CharField(max_length=40, unique=True, db_index=True, null=True, blank=True)
    campaign = models.ForeignKey(DonationCampaign, null=True)

    donation_type = models.CharField(max_length=20, choices=DonationType.DATA_CHOICES)
    amount = models.DecimalField(**decimalfield_kwargs)
    cumulative_amount = models.DecimalField(default=0, **decimalfield_kwargs)
    currency = models.CharField(max_length=7, choices=constants.CURRENCY, default=store_app_settings.DEFAULT_CURRENCY)

    donor_first_name = models.CharField(max_length=200, null=True, blank=True)
    donor_last_name = models.CharField(max_length=200, null=True, blank=True)
    donor_phone_number = models.CharField(max_length=100, null=True, blank=True)
    donor_email = models.EmailField(max_length=200, null=True, blank=True)
    receipt_address = models.CharField(max_length=500, null=True, blank=True)

    date_submitted = models.DateTimeField(null=True)  # Date in which donation is submitted by user
    payment_status = FSMField(default=DonationPaymentStatus.NEW)
    is_confirmed = models.BooleanField(default=False)  # This donation can be accounted for
    cancel_reason = models.CharField(max_length=300, null=True, blank=True)

    paid_transaction = models.OneToOneField('fundraising.StoreTransaction', null=True, related_name='paid_donation')
    payment_provider = models.CharField(max_length=30, blank=True)
    payment_method = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return u'{type} Donation of {amount} {currency} from {donor_fullname} (#{donation_number})'.format(
            type=DonationType.DATA_MAP[self.donation_type]['text'], amount=self.amount, currency=self.currency,
            donor_fullname=self.donor_fullname_or_anonymous, donation_number=self.donation_number)

    objects = DonationManager()

    @property
    def donor_fullname(self):
        if self.donor_first_name or self.donor_last_name:
            return '{0}{1}'.format(self.donor_first_name, ' {}'.format(self.donor_last_name) if self.donor_last_name else '')
        else:
            return self.person.fullname

    @property
    def donor_fullname_or_anonymous(self):
        return self.donor_fullname if self.donor_fullname else donation_app_settings.ANONYMOUS_DONOR_TEXT

    @property
    def charge_amount(self):
        return self.amount

    @property
    def is_recurring(self):
        return self.donation_type == DonationType.RECURRING

    @property
    def recurring_interval__display(self):
        try:
            return self.recurring_instruction.interval__display
        except DonationRecurringInstruction.DoesNotExist:
            return ''

    @property
    def donation_type__display(self):
        return DonationType.DATA_MAP[self.donation_type]['text']

    @property
    def payment_status__display(self):
        return DonationStatus.DATA_MAP[self.payment_status]['text']

    @property
    def payment_method__display(self):
        payment_provider = self.get_payment_provider()
        return payment_provider.get_payment_method_name(self.payment_method)

    # Payment Functions

    def get_payment_provider(self):
        from fundraising.payments.providers import get_payment_provider
        return get_payment_provider(self.payment_provider)

    # Status : NEW => PROCESSING
    @transition(field=payment_status,
                source=DonationPaymentStatus.NEW,
                target=DonationPaymentStatus.PROCESSING)
    def set_payment_status_processing(self):
        pass

    # Status : NEW => OFFLINE_PAYMENT_WAITING
    @transition(field=payment_status,
                source=DonationPaymentStatus.NEW,
                target=DonationPaymentStatus.OFFLINE_PAYMENT_WAITING)
    def set_payment_status_waiting(self):
        pass

    # Status : OFFLINE_PAYMENT_WAITING => OFFLINE_PAYMENT_CONFIRMING
    @transition(field=payment_status,

website/donation/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

website/backyard/forms/donations.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from fundraising.modules.fund_donation.enums import DonationPaymentStatus


class ConfirmaedDonationsSearchForm(forms.Form):
    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))


class IncompleteDonationsSearchForm(forms.Form):
    PAYMENT_STATUS_CHOICES = (
        (DonationPaymentStatus.OFFLINE_PAYMENT_WAITING, DonationPaymentStatus.OFFLINE_PAYMENT_WAITING_TEXT),
        (DonationPaymentStatus.OFFLINE_PAYMENT_DECLINED, DonationPaymentStatus.OFFLINE_PAYMENT_DECLINED_TEXT),
        (DonationPaymentStatus.PAYMENT_FAILED, DonationPaymentStatus.PAYMENT_FAILED_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_STAFF, DonationPaymentStatus.RECURRING_STOPPED_BY_STAFF_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_SYSTEM, DonationPaymentStatus.RECURRING_STOPPED_BY_SYSTEM_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_USER, DonationPaymentStatus.RECURRING_STOPPED_BY_USER_TEXT),
    )

    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    payment_status = forms.MultipleChoiceField(choices=PAYMENT_STATUS_CHOICES, widget=forms.SelectMultiple(attrs={'class': 'form-control'}), required=False)


class AllDonationsSearchForm(forms.Form):
    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    payment_status = forms.MultipleChoiceField(choices=DonationPaymentStatus.DATA_CHOICES, widget=forms.SelectMultiple(attrs={'class': 'form-control'}), required=False)

website/common/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.middleware import csrf
from django.views.decorators.cache import never_cache


@never_cache
def get_form_csrf(request):
    token = csrf.get_token(request)

    return HttpResponse(token)

website/pages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from fundraising.modules.fund_donation.models import DonationCampaign


def homepage(request):
    campaigns = DonationCampaign.objects.ongoing_campaigns()

    return render(request, 'pages/homepage.html', {
        'campaigns': campaigns,
    })

website/views.py
from django.shortcuts import render


def bad_request(request):
    response = render(request, '400.html')
    response.status_code = 400
    return response


def server_error(request):
    response = render(request, '500.html')
    response.status_code = 500
    return response

website/templates/backyard1/donations/donations.html
{% extends 'backyard/listview.html' %}
{% load i18n bootstrap3 common backyard %}

{% block body_css_class %}{{ block.super }} backyard-donations{% endblock %}

{% block page_title %}
  <h1>{{ page.title }}</h1>
  <div class="subtitle">
    {% blocktrans count counter=num_donations %}Total <b>{{ num_donations }}</b> donation{% plural %}Total <b>{{ num_donations }}</b> donations{% endblocktrans %}
  </div>
  <div class="page-actions">
    <a class="btn button-default" href="#"><i class="fa fa-plus-square"></i> {% trans 'Add donation' %}</a> <!-- TODO -->
  </div>
{% endblock %}

{% block list_content %}
    <div class="page-search{% if search_criteria %} searched{% endif %}">
        <form method="get" class="form-inline" action="{{ request.path }}?{{ request.GET.urlencode }}">

            <div class="search-title"><i class="fa fa-chevron-right"></i> {% trans 'Search campaigns' %}...</div>

            <div class="expandable{% if not search_criteria %} hidden{% endif %}">
                <div class="criteria clearfix">
                    <div class="search-criteria">
                        <div class="name"><label for="id_campaign">{% trans 'Campaign' %}</label></div>
                        <div class="value">
                        <div class="form-group">{{ search_form.campaign }}</div>
                    </div>
                </div>
                <div class="search-criteria criteria-keyword">
                    <div class="name"><label for="id_keyword">{% trans 'Donor name, email, phone, address' %}</label></div>
                        <div class="value">
                        <div class="form-group">{{ search_form.keyword }}</div>
                    </div>
                </div>
                </div>
            {% querystring_to_hidden_field request.GET search_criteria %}
            <div class="search-submit">
                <button type="submit" class="btn button-default button-search">{% trans 'Submit' %}</button>
                <a href="{% url 'backyard:store_commerce_donations_page' %}{% querystring_only request.GET 'status' %}" class="btn button-default button-reset">{% trans 'Reset' %}</a>
            </div>
            </div>
        </form>
    </div>

  <div class="page-filters">
    <span class="name">{% trans 'Payment status' %}:</span>
    <span role="group" aria-label="...">
      <a href="{% url 'backyard:store_commerce_campaigns_page' %}{% querystring_include request.GET 'method' %}" class="{% if not filter_by_status %} active{% endif %}">{% trans 'All donations' %}</a>
      <span class="sep">|</span>
      <a href="{% url 'backyard:store_commerce_campaigns_page' %}{% querystring_include request.GET 'method' 'draft' %}" class="{% if filter_by_status == 'draft' %} active{% endif %}">{% trans 'Paid or Active Recurring' %}</a>
      <span class="sep">|</span>
      <a href="{% url 'backyard:store_commerce_campaigns_page' %}{% querystring_include request.GET 'method' 'ongoing' %}" class="{% if filter_by_status == 'ongoing' %} active{% endif %}">{% trans 'Waiting to confirm' %}</a>
      <span class="sep">|</span>
      <a href="{% url 'backyard:store_commerce_campaigns_page' %}{% querystring_include request.GET 'method' 'closed' %}" class="{% if filter_by_status == 'closed' %} active{% endif %}">{% trans 'Recurring Stopped' %}</a>
    <span class="sep">|</span>
      <a href="{% url 'backyard:store_commerce_campaigns_page' %}{% querystring_include request.GET 'method' 'closed' %}" class="{% if filter_by_status == 'closed' %} active{% endif %}">{% trans 'Refunded' %}</a>
    </span>
  </div>



{% comment %}
  <div class="page-search clearfix">
    <form method="get" class="form-inline">
      <div class="search-criteria">
        <div class="name">ค้นหาตามโครงการ</div>
        <div class="value">
          <button type="button" class="btn button-default" data-toggle="modal" data-target="#modal_campaigns">เลือกโครงการ</button>
          <div class="js-input-campaign hidden">
              {% for campaign_id in selected_campaigns %}
                  <input type="hidden" name="campaign" value="{{ campaign_id }}" />
              {% endfor %}
          </div>
        </div>
      </div>

      <div class="search-criteria duration-criteria">
        <div class="name"><label for="id_from_date_confirmed">วันที่บริจาค</label></div>
        <div class="value">
          <div class="form-group form-duration">
            <div class="input-group">
              {{ form.from_date }}
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
            <span class="fromto">to</span>
            <div class="input-group">
              {{ form.to_date }}
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
          </div>
        </div>
      </div>

      <div class="search-criteria">
        <div class="name"><label for="id_keyword">เลขที่บริจาค, อีเมล</label></div>
        <div class="value">
          <div class="form-group">
            {{ form.keyword }}
          </div>
        </div>
      </div>

      <div class="search-submit">
        <button type="submit" class="btn button-primary"><i class="fa fa-filter"></i> ค้นหา</button>
        <a href="{% url 'backyard:store_commerce_donations_page' %}" class="btn button-default">เริ่มใหม่</a>
      </div>
    </form>
  </div>
  {% endcomment %}

  {% comment %}
  <div class="page-searched">
    <div class="box">
      <h3>ค้นเจอ 10 รายการบริจาคตามเงื่อนไข</h3>
      <ul>
        <li><span class="criteria">โครงการ :</span> อะไรซักอย่างก็ได้</li>
      </ul>
      <!--<div class="clearall">
        <a href="#"><i class="fa fa-close"></i> ล้างเงื่อนไขการค้นหา</a>
      </div>-->
    </div>
  </div>
  {% endcomment %}

{% comment %}
  <div class="table-count">
    Found <b>{{ page_obj.paginator.count }}</b> donations
  </div>{% endcomment %}

  {% if object_list %}
    <table class="table table-default table-donations">
      <thead>
      <tr>
        <th class="datetime">{% trans 'Donation date' %}</th>
        <th class="donor">{% trans 'Donor name' %}</th>
        <th class="campaign">{% trans 'Campaign' %}</th>
        <th class="amount">{% trans 'Amount' %} <span class="unit">({% trans 'Baht' %})</span></th>
        <th class="type">{% trans 'Donation type' %}</th>
        <th class="method">{% trans 'Payment method' %}</th>
        <th class="status">{% trans 'Status' %}</th>
      </tr>
      </thead>
      <tbody>

      {% for donation in object_list %}
        <tr class="clickable-row">
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.date_confirmed|display_datetime }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.donor_fullname_or_anonymous }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.campaign.name }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.amount|display_amount }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.donation_type__display }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.payment_method__display }}</a></td>
          <td class="status-cell"><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}"><i class="fa fa-check-circle"></i> {{ donation.status__display }}</a></td>  <!-- fa-question-circle -->
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="no-objects">ไม่มีรายการบริจาค</div>
  {% endif %}
{% endblock %}

{% block javascript %}
{{ block.super }}

<script>
$('.search-title').on('click', function() {
  var expandable = $(this).parent().find('.expandable');

  if(expandable.hasClass('hidden')) {
    expandable.removeClass('hidden').hide();
  }

  if(expandable.is(':visible')) {
    expandable.slideUp('fast');
    $(this).find('i').removeClass('fa-rotate-90');

  } else {
    expandable.slideDown('fast');
    $(this).find('i').addClass('fa-rotate-90');
  }
});
</script>
{% endblock %}

website/templates/backyard1/donations/recurring_donations.html
{% extends 'backyard/listview.html' %}
{% load humanize bootstrap3 common %}

{% block body_css_class %}{{ block.super }} backyard-donations{% endblock %}

{% block list_content %}
  <div class="page-search clearfix">
    <form method="get" class="form-inline">
      <div class="search-criteria">
        <div class="name">ค้นหาตามโครงการ</div>
        <div class="value">
          <button type="button" class="btn button-default" data-toggle="modal" data-target="#modal_campaigns">เลือกโครงการ</button>
          <div class="js-input-campaign hidden">
              {% for campaign_id in selected_campaigns %}
                  <input type="hidden" name="campaign" value="{{ campaign_id }}" />
              {% endfor %}
          </div>
        </div>
      </div>

      <div class="search-criteria duration-criteria">
        <div class="name"><label for="id_from_date_confirmed">วันที่เริ่มบริจาค</label></div>
        <div class="value">
          <div class="form-group form-duration">
            <div class="input-group">
              {{ form.from_date }}
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
            <span class="fromto">to</span>
            <div class="input-group">
              {{ form.to_date }}
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
          </div>
        </div>
      </div>

      <div class="search-criteria">
        <div class="name"><label for="id_keyword">เลขที่บริจาค, อีเมล</label></div>
        <div class="value">
          <div class="form-group">
            {{ form.keyword }}
          </div>
        </div>
      </div>

      <div class="search-submit">
        <button type="submit" class="btn button-primary"><i class="fa fa-filter"></i> ค้นหา</button>
        <a href="{% url 'backyard:store_commerce_recurring_donations_page' %}" class="btn button-default">เริ่มใหม่</a>
      </div>
    </form>
  </div>

  {% comment %}
  <div class="table-count">
    Found <b>{{ page_obj.paginator.count }}</b> donations
  </div>{% endcomment %}

  {% if object_list %}
    <table class="table table-default">
      <thead>
      <tr>
        <th class="date">วันที่เริ่มบริจาค</th>
        <th class="name">ชื่อหรืออีเมล</th>
        <th class="name">โครงการ</th>
        <th class="type">สถานะ</th>
        <th class="amount">จำนวนเงิน <span class="unit">(บาท)</span></th>
      </tr>
      </thead>
      <tbody>

      {% for donation in object_list %}
        <tr class="clickable-row">
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.date_confirmed|date:'j M Y' }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.donor.display_name_or_email }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.campaign.name }}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{% if donation.recurring_instruction.is_active %}<span class="is_active">กำลังบริจาค</span>{% else %}<span class="is_inactive">หยุดการบริจาค</span>{% endif %}</a></td>
          <td><a href="{% url 'backyard:store_commerce_donation_details_page' number=donation.donation_number %}">{{ donation.amount|amount_short }}</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="no-objects">ไม่มีรายการบริจาค</div>
  {% endif %}
{% endblock %}

{% block javascript %}
{{ block.super }}

<script>
$('#id_from_date').datepicker({
  format: 'dd/mm/yyyy',
  autoclose: true,
  todayHighlight: true
});

$('#id_to_date').datepicker({
  format: 'dd/mm/yyyy',
  autoclose: true,
  todayHighlight: true
});
</script>
{% endblock %}