config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

import backyard

from website.views import bad_request, server_error

urlpatterns = [
    # Languages
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Django Admin
    url(settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^backend/', include(backyard.get_urls(), namespace='backyard')),
    url(r'', include('fundraising.urls', namespace='fundraising')),

    # url(r'', include('fundraising.modules.store_commerce.urls', namespace='store_commerce')),

    url(r'', include('website.common.urls', namespace='common')),
    url(r'', include('website.pages.urls', namespace='pages')),
    url(r'', include('website.donations.urls', namespace='donations')),

    url(r'^summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'website.views.bad_request'
handler500 = 'website.views.server_error'

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', bad_request),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', server_error),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

website/common/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^form/csrf/$', view=views.get_form_csrf, name='form_csrf'),
]

website/donation/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^listing/$', view=views.listing, name='listing'),
    url(r'^product/(?P<product_id>\d+)/$', view=views.product_view, name='product_view'),

    url(r'^cart/$', view=views.cart_view, name='cart_view'),

    url(r'^checkout/$', view=views.checkout, name='checkout'),
    url(r'^checkout/payment/$', view=views.checkout_payment, name='checkout_payment'),

    url(r'^order/(?P<order_number>\w+)/$', view=views.order_details, name='order_details'),

]

website/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', view=views.homepage, name='homepage'),

]

website/donation/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

website/common/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.middleware import csrf
from django.views.decorators.cache import never_cache


@never_cache
def get_form_csrf(request):
    token = csrf.get_token(request)

    return HttpResponse(token)

website/donation/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from fundraising.modules.store_commerce.functions import get_functions as commerce_fn
from fundraising.modules.store_commerce.models import Product, Cart, Order

from .forms import CheckoutForm


def listing(request):
    products = Product.objects.published()

    return render(request, 'pages/listing.html', {
        'products': products,
    })


def product_view(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if not product.is_published:
        raise Http404

    return render(request, 'pages/product_page.html', {
        'product': product,
    })


def cart_view(request):
    cart = Cart.objects.get_from_request(request)
    cart.update()

    return render(request, 'pages/cart.html', {

    })


def checkout(request):
    cart = Cart.objects.get_from_request(request)

    if not cart or cart.is_empty:
        return redirect('commerce:cart_view')

    if request.method == 'POST':
        checkout_form = CheckoutForm(request.POST)

        if checkout_form.is_valid():
            checkout_form.save(cart)
            return redirect('commerce:checkout_payment')

    else:
        initial = {}
        if cart.shopper:
            shopper = cart.shopper
            initial.update({
                'first_name': shopper.first_name,
                'last_name': shopper.last_name,
                'email': shopper.email,
            })

        if cart.shipping_address:
            shipping_address = cart.shipping_address
            initial.update({
                'phone_number': shipping_address.phone_number,
                'address': shipping_address.address,
                'city': shipping_address.city,
                'province': shipping_address.province,
                'zip_code': shipping_address.zip_code,
            })

        checkout_form = CheckoutForm(initial=initial)

    return render(request, 'commerce/checkout.html', {
        'checkout_form': checkout_form,
    })


def checkout_payment(request):
    cart = Cart.objects.get_from_request(request)

    if request.method == 'POST':
        order = commerce_fn.checkout(cart)

        if order.total == 0:
            order.set_no_payment_required()

        else:

            # DUMMY : Assume payment is collected right away
            order.set_payment_paid()

            # request.session[''] = ''  # TODO : Add success message after purchase

        order.save()

        commerce_fn.unlink_cart(request)

        # TODO : Clear cart

        return redirect('commerce:order_details', order_number=order.order_number)

    return render(request, 'commerce/checkout_payment.html', {})


def order_details(request, order_number):
    order = Order.objects.get(order_number=order_number)

    return render(request, 'commerce/order_details.html', {
        'order': order,
    })

website/donations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _

from fundraising.models import Person
from fundraising.modules.fund_donation.models import DonationCampaign, Donation
from fundraising.payments.exceptions import PaymentException
from fundraising.payments.omise.exceptions import OMISE_ERROR_CODES

from website.donations.forms import DonationForm, PaymentFormError


def _donate_view(request, campaign=None):
    if request.method == 'POST':
        if campaign and not campaign.is_able_to_donate:
            # TODO : Add django message saying 'This campaign is closed for donation'
            return redirect(campaign.get_absolute_url())

        post_data = request.POST.dict()
        if request.user.is_authenticated:
            post_data.update({
                'email': request.user.email,
            })

        form = DonationForm(campaign=campaign, data=post_data)
        if form.is_valid():

            try:
                donation = form.save(request)
                return redirect('donations:thankyou', donation_number=donation.donation_number)

            except PaymentFormError as e:
                if e.field:
                    form.add_field_error(e.field, e.message)
                else:
                    form.add_non_field_error(e.message)

    else:
        initial_data = {}

        if request.user.is_authenticated():
            user = request.user

            try:
                person = Person.objects.get(user=user)
            except Person.DoesNotExist:
                person = Person()

            initial_data.update({
                'first_name': person.first_name if person.first_name else user.first_name,
                'last_name': person.last_name if person.last_name else user.last_name,
                'email': person.email if person.email else user.email,
                'phone_number': person.phone_number,
                'address': person.receipt_address,
            })

        form = DonationForm(campaign=campaign, initial=initial_data)

    return render(request, 'donations/donate.html', {
        'campaign': campaign,
        'form': form,
    })


def donate(request):
    return _donate_view(request, None)


def donate_by_campaign(request, campaign_id, campaign_slug):
    if campaign_id:
        campaign = get_object_or_404(DonationCampaign, pk=campaign_id)
    elif campaign_slug:
        campaign = get_object_or_404(DonationCampaign, slug=campaign_slug)
    else:
        raise Http404

    if not campaign.is_public:
        if not request.user.is_authenticated or not request.user.is_superuser:
            raise Http404

    return _donate_view(request, campaign)


"""
    if request.method == 'POST':
        post_data = request.POST.dict()
        if request.user.is_authenticated:
            post_data.update({
                'email': request.user.email,
            })

        form = DonationForm(campaign=None, data=post_data)
        if form.is_valid():

            try:
                donation = form.save(request)
                return redirect('donations:thankyou', donation_number=donation.donation_number)

            except PaymentFormError as e:
                if e.field:
                    form.add_field_error(e.field, e.message)
                else:
                    form.add_non_field_error(e.message)

    else:
        initial_data = {
            'amount_choice': 1000,
            'payment_option': '',
        }

        if request.user.is_authenticated():
            user = request.user

            try:
                person = Person.objects.get(user=user)
            except Person.DoesNotExist:
                person = Person()

            initial_data.update({
                'first_name': person.first_name if person.first_name else user.first_name,
                'last_name': person.last_name if person.last_name else user.last_name,
                'email': person.email if person.email else user.email,
                'phone_number': person.phone_number,
                'address': person.receipt_address,
            })

        form = DonationForm(campaign=None, initial=initial_data)

    return render(request, 'donations/donate.html', {
        'form': form,
    })
"""

"""
    if request.method == 'POST':
        if not campaign.is_able_to_donate:
            # TODO : Add django message saying 'This campaign is closed for donation'
            return redirect(campaign.get_absolute_url())

        post_data = request.POST.dict()
        if request.user.is_authenticated:
            post_data.update({
                'email': request.user.email,
            })

        form = SimpleDonationForm(request, post_data)

        if form.is_valid():
            donation = form.save(request, campaign)

            if donation.payment_provider == 'omise':
                provider = donation.payment_provider_object

                omise_token = request.POST.get('omise_token')
                omise_card_id = request.POST.get('omise_card_id')

                if omise_token and omise_card_id:
                    try:
                        omise_customer_card = provider.create_customer_with_card(donation.donor, omise_token,
                                                                                 omise_card_id)

                    except PaymentException as e:
                        form.add_form_error(e.message)

                    else:
                        omise_transaction = provider.charge_card(donation, omise_customer_card)

                        if omise_transaction.action_status == StoreTransactionStatus.SUCCESS:
                            donation.set_to_paid(omise_transaction)
                        else:
                            donation.set_to_failed(omise_transaction)
                            form.add_form_error(omise_transaction.fail_message)

                        if donation.status in (DonationStatus.PAID, DonationStatus.RECURRING):
                            return redirect('donations:thankyou', donation_number=donation.donation_number)

                        else:
                            try:
                                error_msg = OMISE_ERROR_CODES[omise_transaction.fail_code]
                            except KeyError:
                                error_msg = \
                                    _('Cannot process this credit card. Please try again or change to another card.')

                            form.add_form_error(omise_transaction.fail_message)

                else:
                    form.add_form_error('Missing token')

            elif donation.payment_provider == 'linepay':
                pass

            elif donation.payment_provider == 'transfer':
                pass

            else:
                raise Http404

            return redirect('donations:thankyou', donation.donation_number)

    else:
        if request.user.is_authenticated():
            user = request.user

            try:
                person = Person.objects.get(user=user)
            except Person.DoesNotExist:
                person = Person()

            initial_data = {
                'first_name': person.first_name if person.first_name else user.first_name,
                'last_name': person.last_name if person.last_name else user.last_name,
                'email': person.email if person.email else user.email,
                'phone_number': person.phone_number,
                'address': person.receipt_address,
            }

        else:
            initial_data = {}

        form = SimpleDonationForm(request, initial=initial_data)

    return render(request, 'donations/campaign.html', {
        'campaign': campaign,
        'form': form,
    })
"""

"""
def donate_by_campaign(request, campaign_id, campaign_slug):

    if campaign_id:
        campaign = get_object_or_404(DonationCampaign, pk=campaign_id)
    elif campaign_slug:
        campaign = get_object_or_404(DonationCampaign, slug=campaign_slug)
    else:
        raise Http404

    if not campaign.is_visible_to_user:
        if not request.user.is_authenticated or not request.user.is_superuser:
            raise Http404

    if request.method == 'POST':
        if not campaign.is_able_to_donate:
            # TODO : Add django message saying 'This campaign is closed for donation'
            return redirect(campaign.get_absolute_url())

        post_data = request.POST.dict()
        if request.user.is_authenticated:
            post_data.update({
                'email': request.user.email,
            })

        form = DonationForm(post_data)

        if form.is_valid():
            donation = form.save(request, campaign)
            payment_option = form.cleaned_data.get('payment_option')

            if payment_option == 'creditcard':
                provider = get_payment_provider('omise')

                omise_token = request.POST.get('omise_token')
                omise_card_id = request.POST.get('omise_card_id')

                if omise_token and omise_card_id:
                    try:
                        omise_customer_card = provider.create_customer_with_card(donation.donor, omise_token,
                                                                                 omise_card_id)

                    except PaymentException as e:
                        form.add_form_error(e.message)

                    else:
                        if donation.is_recurring:
                            # Initial charge on the day of donation submitted
                            omise_transaction = provider.charge_card(donation, omise_customer_card)

                            if omise_transaction.action_status == StoreTransactionStatus.SUCCESS:

website/pages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from fundraising.modules.fund_donation.models import DonationCampaign


def homepage(request):
    campaigns = DonationCampaign.objects.ongoing_campaigns()

    return render(request, 'pages/homepage.html', {
        'campaigns': campaigns,
    })

website/views.py
from django.shortcuts import render


def bad_request(request):
    response = render(request, '400.html')
    response.status_code = 400
    return response


def server_error(request):
    response = render(request, '500.html')
    response.status_code = 500
    return response

website/templates/base.html
{% load staticfiles compress %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Fundraising Platform{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">

    <!-- Facebook -->
    {% block facebook_meta %}
        <meta property="og:url" content="{{ WEBSITE_URL }}"/>
        <meta property="og:type" content="website"/>
        <meta property="og:title" content=""/>
        <meta property="og:description" content=""/>
        <meta property="og:image" content="http://www.example.com/path/image.jpg"/>
    {% endblock %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% if debug %}
        <link href="{% static 'libs/tether/css/tether.min.css' %}" rel="stylesheet">
        <link href="{% static 'libs/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    {% else %}
        <link href="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/css/tether.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% endif %}

  {% compress css %}
        <link  href="{% static 'libs/bank/css/thbanklogos.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        {% block css %}
        {% endblock css %}
  {% endcompress %}
</head>

<body class="{% block body_css_class %}{% endblock %}">
    {% block content %}{% endblock %}

    {% if debug %}
        <script src="{% static 'libs/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'libs/tether/js/tether.min.js' %}"></script>
        <script src="{% static 'libs/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'libs/dropzone/dropzone.js' %}"></script>
        <script src="{% static 'libs/ramda.min.js' %}"></script>
        <script src="{% static 'libs/store/store2.min.js' %}"></script>
    {% else %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/min/dropzone.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ramda/0.23.0/ramda.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/store2/2.5.0/store2.min.js"></script>
    {% endif %}

    {% compress js %}
        <script src="{% static 'libs/jquery.payment.min.js' %}"></script>
        <script src="{% static 'libs/exif.js' %}"></script>
        <script src="{% static 'libs/omise/vendor/easyXDM.js' %}"></script>
        <script src="{% static 'libs/omise/omise.js' %}"></script>

        <script src="{% static 'libs/store/store.array.js' %}"></script>

        <script src="{% static 'js/base.js' %}"></script>
        <script src="{% static 'js/remove_hash.js' %}"></script>
        <script src="{% static 'js/uploader.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>

        {% block javascript %}
        {% endblock javascript %}
    {% endcompress %}
</body>
</html>

website/templates/base_email.html
{% load static common %}
<!DOCTYPE html>
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<style type="text/css">
/* CLIENT-SPECIFIC STYLES */
body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
img { -ms-interpolation-mode: bicubic; }

/* RESET STYLES */
img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
table { border-collapse: collapse !important; }
body { height: 100% !important; margin: 0 !important; padding: 0 !important; width: 100% !important; }

/* iOS BLUE LINKS */
a[x-apple-data-detectors] {
    color: inherit !important;
    text-decoration: none !important;
    font-size: inherit !important;
    font-family: inherit !important;
    font-weight: inherit !important;
    line-height: inherit !important;
}

/* MEDIA QUERIES */
@media screen and (max-width: 480px) {
    .mobile-hide {
        display: none !important;
    }
    .mobile-center {
        text-align: center !important;
    }
}

/* ANDROID CENTER FIX */
div[style*="margin: 16px 0;"] { margin: 0 !important; }
</style>
</head>
<body style="margin: 0 !important; padding: 0 !important; background-color: #f7f7f7;" bgcolor="#f7f7f7">

<!-- HIDDEN PREHEADER TEXT -->
<div style="display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: Open Sans, Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;">
{% block preheader_text %}{% endblock %}
</div>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" style="background-color: #f7f7f7;" bgcolor="#f7f7f7">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellspacing="0" cellpadding="0" width="700">
        <tr>
        <td align="center" valign="top" width="700">
        <![endif]-->
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:700px;">
            <tr>
                <td align="center" valign="top" style="font-size:0; padding: 0 35px 18px;border-bottom: 2px solid #f8daa7;" bgcolor="#FFF8EC">
                <!--[if (gte mso 9)|(IE)]>
                <table align="center" border="0" cellspacing="0" cellpadding="0" width="700">
                <tr>
                <td align="center" valign="top" width="700">
                <![endif]-->
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:700px;">
                    <tr>
                        <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 20px;">
                            <h1 style="margin: 0;"><img src="{% get_settings 'WEBSITE_URL' %}{% static 'images/email/taejai-logo.png' %}" width="70" height="73" alt="Taejai.com"/></h1>
                        </td>
                    </tr>
                </table>
                <!--[if (gte mso 9)|(IE)]>
                </td>
                </tr>
                </table>
                <![endif]-->
                </td>
            </tr>
            <tr>
                <td align="center" style="padding: 35px 35px 0 35px; background-color: #ffffff;" bgcolor="#ffffff">
                <!--[if (gte mso 9)|(IE)]>
                <table align="center" border="0" cellspacing="0" cellpadding="0" width="700">
                <tr>
                <td align="center" valign="top" width="700">
                <![endif]-->
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:700px;">
                    <tr>
                        <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif;">
                            {% block head_image_url %}{% endblock %}
                            <h2 style="font-size: 30px; font-weight: 800; line-height: 30px; color: #333333; margin: 0;">
                                {% block head_title %}{% endblock %}
                            </h2>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif;">
                            <p style="font-size: 16px; font-weight: 400; line-height: 27px; color: #444444;">{% block head_subtitle %}{% endblock %}</p>
                            {% block head_more_subtitle %}{% endblock %}
                        </td>
                    </tr>
                    {% block email_upper_body %}{% endblock %}
                </table>
                <!--[if (gte mso 9)|(IE)]>
                </td>
                </tr>
                </table>
                <![endif]-->
                </td>
            </tr>

            <tr>
                <td align="left" height="100%" valign="top" width="100%" style="padding: 20px 35px 0 35px; background-color: #ffffff;" bgcolor="#ffffff">
                <!--[if (gte mso 9)|(IE)]>
                <table align="left" border="0" cellspacing="0" cellpadding="0" width="700">
                <tr>
                <td align="left" valign="top" width="700">
                <![endif]-->
                    {% block email_body %}{% endblock %}
                <!--[if (gte mso 9)|(IE)]>
                </td>
                </tr>
                </table>
                <![endif]-->
                </td>
            </tr>

            <tr>
                <td align="center" style="padding: 35px; background-color: #ffffff;" bgcolor="#ffffff">
                <!--[if (gte mso 9)|(IE)]>
                <table align="center" border="0" cellspacing="0" cellpadding="0" width="700">
                <tr>
                <td align="center" valign="top" width="700">
                <![endif]-->
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:700px;">
                    <tr>
                        <td align="center">
                            <img src="{% get_settings 'WEBSITE_URL' %}{% static 'images/email/taejai-logo.png' %}" width="57" height="60" style="display: block; border: 0px;"/>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
                            <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">
                                เว็บไซต์เทใจดอทคอม<br><span style="font-weight: 400; line-height: 30px; color: #777777;">{% get_settings 'WEBSITE_URL' %}</span>
                            </p>
                        </td>
                    </tr>
                </table>
                <!--[if (gte mso 9)|(IE)]>
                </td>
                </tr>
                </table>
                <![endif]-->
                </td>
            </tr>
        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
        </td>
    </tr>
</table>
</body>
</html>

website/templates/base_error.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}UNDP Donation{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">

  <link href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/styles.css' %}" rel="stylesheet">

</head>
<body class="{% block body_css_class %}{% endblock %}">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'pages:homepage' %}">UNDP Donation</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'pages:homepage' %}">Home <span class="sr-only">(current)</span></a></li>
      </ul>
    </div>
  </div>
</nav>

{% block content %}{% endblock %}

<script src="{% static 'libs/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

website/templates/base_inner.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Logo & Main navigation -->
    <nav class="navbar navbar-toggleable-md navbar-inner">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'pages:homepage' %}"><img src="{% static 'images/website/logo-black.png' %}" width="215" height="36" /></a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">What we do</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Campaigns</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Updates</a>
                </li>
            </ul>
            <div class="nav-actions">
                <a href="#" class="nav-link btn btn-action-outline">What can you help?</a>
            </div>
        </div>
    </nav>

    {% if messages %}
    <ul class="block-messages">
        {% for message in messages %}
            <li class="alert{% if message.tags %}  alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="page-inner-content">{% block content_inner %}{% endblock %}</div>
{% endblock %}