config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

import backyard

from website.views import bad_request, server_error

urlpatterns = [
    # Languages
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Django Admin
    url(settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^backend/', include(backyard.get_urls(), namespace='backyard')),
    url(r'', include('fundraising.urls', namespace='fundraising')),

    # url(r'', include('fundraising.modules.store_commerce.urls', namespace='store_commerce')),

    url(r'', include('website.common.urls', namespace='common')),
    url(r'', include('website.pages.urls', namespace='pages')),
    url(r'', include('website.donations.urls', namespace='donations')),

    url(r'^summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'website.views.bad_request'
handler500 = 'website.views.server_error'

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', bad_request),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', server_error),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

website/common/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^form/csrf/$', view=views.get_form_csrf, name='form_csrf'),
]

website/donation/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^listing/$', view=views.listing, name='listing'),
    url(r'^product/(?P<product_id>\d+)/$', view=views.product_view, name='product_view'),

    url(r'^cart/$', view=views.cart_view, name='cart_view'),

    url(r'^checkout/$', view=views.checkout, name='checkout'),
    url(r'^checkout/payment/$', view=views.checkout_payment, name='checkout_payment'),

    url(r'^order/(?P<order_number>\w+)/$', view=views.order_details, name='order_details'),

]

website/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', view=views.homepage, name='homepage'),

]

website/donation/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

website/backyard/forms/donations.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from fundraising.modules.fund_donation.enums import DonationPaymentStatus


class ConfirmaedDonationsSearchForm(forms.Form):
    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))


class IncompleteDonationsSearchForm(forms.Form):
    PAYMENT_STATUS_CHOICES = (
        (DonationPaymentStatus.OFFLINE_PAYMENT_WAITING, DonationPaymentStatus.OFFLINE_PAYMENT_WAITING_TEXT),
        (DonationPaymentStatus.OFFLINE_PAYMENT_DECLINED, DonationPaymentStatus.OFFLINE_PAYMENT_DECLINED_TEXT),
        (DonationPaymentStatus.PAYMENT_FAILED, DonationPaymentStatus.PAYMENT_FAILED_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_STAFF, DonationPaymentStatus.RECURRING_STOPPED_BY_STAFF_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_SYSTEM, DonationPaymentStatus.RECURRING_STOPPED_BY_SYSTEM_TEXT),
        (DonationPaymentStatus.RECURRING_STOPPED_BY_USER, DonationPaymentStatus.RECURRING_STOPPED_BY_USER_TEXT),
    )

    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    payment_status = forms.MultipleChoiceField(choices=PAYMENT_STATUS_CHOICES, widget=forms.SelectMultiple(attrs={'class': 'form-control'}), required=False)


class AllDonationsSearchForm(forms.Form):
    keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Number, Name, Email'}), required=False)
    date_submitted_range = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    payment_status = forms.MultipleChoiceField(choices=DonationPaymentStatus.DATA_CHOICES, widget=forms.SelectMultiple(attrs={'class': 'form-control'}), required=False)

website/donation/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.core import validators

from fundraising.constants import TH_PROVINCE_CHOICES
from fundraising.modules.store_commerce.models import Cart

"""
class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(validators=[validators.MinValueValidator(1)])

    def save(self, request, product):
        cart = Cart.objects.get_or_create_from_request(request)
        quantity = self.cleaned_data['quantity']
        return cart.add_product_to_cart(product, quantity)
"""


class CheckoutForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    # Address
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    province = forms.ChoiceField(choices=TH_PROVINCE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    zip_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def save(self, cart):
        cart.update_shopper(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            email=self.cleaned_data['email']
        )

        fullname = '{} {}'.format(self.cleaned_data['first_name'], self.cleaned_data['last_name'])

        cart.update_shipping_address(
            fullname=fullname,
            address=self.cleaned_data['address'],
            city=self.cleaned_data['city'],
            province=self.cleaned_data['province'],
            country='TH',
            zip_code=self.cleaned_data['zip_code'],
            phone_number=self.cleaned_data['phone_number'],
        )

        cart.update_billing_address(
            fullname=fullname,
            address=self.cleaned_data['address'],
            city=self.cleaned_data['city'],
            province=self.cleaned_data['province'],
            country='TH',
            zip_code=self.cleaned_data['zip_code'],
            phone_number=self.cleaned_data['phone_number'],
        )

        return cart


class CheckoutPaymentForm(forms.Form):
    pass

website/common/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.middleware import csrf
from django.views.decorators.cache import never_cache


@never_cache
def get_form_csrf(request):
    token = csrf.get_token(request)

    return HttpResponse(token)

website/donation/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from fundraising.modules.store_commerce.functions import get_functions as commerce_fn
from fundraising.modules.store_commerce.models import Product, Cart, Order

from .forms import CheckoutForm


def listing(request):
    products = Product.objects.published()

    return render(request, 'pages/listing.html', {
        'products': products,
    })


def product_view(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if not product.is_published:
        raise Http404

    return render(request, 'pages/product_page.html', {
        'product': product,
    })


def cart_view(request):
    cart = Cart.objects.get_from_request(request)
    cart.update()

    return render(request, 'pages/cart.html', {

    })


def checkout(request):
    cart = Cart.objects.get_from_request(request)

    if not cart or cart.is_empty:
        return redirect('commerce:cart_view')

    if request.method == 'POST':
        checkout_form = CheckoutForm(request.POST)

        if checkout_form.is_valid():
            checkout_form.save(cart)
            return redirect('commerce:checkout_payment')

    else:
        initial = {}
        if cart.shopper:
            shopper = cart.shopper
            initial.update({
                'first_name': shopper.first_name,
                'last_name': shopper.last_name,
                'email': shopper.email,
            })

        if cart.shipping_address:
            shipping_address = cart.shipping_address
            initial.update({
                'phone_number': shipping_address.phone_number,
                'address': shipping_address.address,
                'city': shipping_address.city,
                'province': shipping_address.province,
                'zip_code': shipping_address.zip_code,
            })

        checkout_form = CheckoutForm(initial=initial)

    return render(request, 'commerce/checkout.html', {
        'checkout_form': checkout_form,
    })


def checkout_payment(request):
    cart = Cart.objects.get_from_request(request)

    if request.method == 'POST':
        order = commerce_fn.checkout(cart)

        if order.total == 0:
            order.set_no_payment_required()

        else:

            # DUMMY : Assume payment is collected right away
            order.set_payment_paid()

            # request.session[''] = ''  # TODO : Add success message after purchase

        order.save()

        commerce_fn.unlink_cart(request)

        # TODO : Clear cart

        return redirect('commerce:order_details', order_number=order.order_number)

    return render(request, 'commerce/checkout_payment.html', {})


def order_details(request, order_number):
    order = Order.objects.get(order_number=order_number)

    return render(request, 'commerce/order_details.html', {
        'order': order,
    })

website/pages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from fundraising.modules.fund_donation.models import DonationCampaign


def homepage(request):
    campaigns = DonationCampaign.objects.ongoing_campaigns()

    return render(request, 'pages/homepage.html', {
        'campaigns': campaigns,
    })

website/views.py
from django.shortcuts import render


def bad_request(request):
    response = render(request, '400.html')
    response.status_code = 400
    return response


def server_error(request):
    response = render(request, '500.html')
    response.status_code = 500
    return response

website/templates/commerce/checkout.html
{% extends "base.html" %}
{% load common i18n %}

{% block body_css_class %}page-checkout-shopper{% endblock %}

{% block title %}Checkout - Shopper{% endblock title %}

{% block content %}
<div class="container-fluid">
    <h1>Checkout - Shopper details</h1>

    <form action="." method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="id_email">Email address</label>
                    {{ checkout_form.email }}
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                <div class="form-group">
                    <label for="id_first_name">First name</label>
                    {{ checkout_form.first_name }}
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="id_last_name">Last name</label>
                    {{ checkout_form.last_name }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                <div class="form-group">
                    <label for="id_phone_number">Phone number</label>
                    {{ checkout_form.phone_number }}
                    <small id="emailHelp" class="form-text text-muted">We might contact you when we are delivery.</small>
                </div>
            </div>
        </div>

        <h3>Shipping address</h3>

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="id_address">Street address</label>
                    {{ checkout_form.address }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                <div class="form-group">
                    <label for="id_city">City</label>
                    {{ checkout_form.city }}
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="id_province">Province</label>
                    {{ checkout_form.province }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <div class="form-group">
                    <label for="id_zip_code">Zip code</label>
                    {{ checkout_form.zip_code }}
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Next</button>
    </form>
</div>

<div class="modal fade" id="cartOutOfSyncModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="backToCartModalLabel">Your cart has a change.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Continue</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}



{% block javascript %}
<script>
if(ShoppingCart.is_out_of_sync) {
    $('#cartOutOfSyncModal').modal('show');
}



/*
var dbTimestamp = {{ shopping_cart.last_updated_milliseconds | default:0 }};
if (dbTimestamp < ShoppingCart.last_updated) {
    $('#backToCartModal').modal('show');
}

$('#cartOutOfSyncModal').on('hide.bs.modal', function (e) {
    window.location = "{% url 'commerce:cart_view' %}";
});*/

</script>
{% endblock %}

website/templates/commerce/checkout_payment.html
{% extends "base.html" %}
{% load common i18n %}

{% block body_css_class %}page-checkout-payment{% endblock %}

{% block title %}Checkout - Payment{% endblock title %}

{% block content %}
<div class="container-fluid">
    <h1>Checkout - Payment</h1>

    <form action="." method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-6">
                <fieldset class="form-group">
                    <legend>Payment method</legend>
                    <div class="form-check">
                      <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                        Credit Card
                      </label>
                    </div>
                    <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                        LINE Pay
                      </label>
                    </div>
                    <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios3" value="option3" disabled>
                        Bank Transfer
                      </label>
                    </div>
                </fieldset>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Next</button>

    </form>
</div>
{% endblock %}

website/templates/commerce/order_details.html
{% extends "base.html" %}
{% load common i18n %}

{% block body_css_class %}page-order-details{% endblock %}

{% block title %}Order details{% endblock title %}

{% block content %}
<div class="container-fluid">
    <h1>Order details # {{ order.order_number }}</h1>

    {{ order.subtotal }}
    {{ order.total }}

</div>
{% endblock %}

website/templates/commerce/thankyou.html
{% extends "base.html" %}
{% load common static %}

{% block body_css_class %}page-donations-thankyou{% endblock %}

{% block facebook_meta %}
  <meta property="og:url" content="{{ WEBSITE_URL }}"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content=""/>
  <meta property="og:description" content=""/>
  <meta property="og:image" content="http://www.example.com/path/image.jpg"/>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-2 col-md-1"></div>
    <div class="col-lg-8 col-md-10">

      <h1>Thank you for trying our demo</h1>
      <div class="subtitle">We have sent you an email to <b>panuta@gmail.com</b> to let you check out the customizable confirmation email that donors will receive.</div>

      <div class="sharing">
        <p>Share your donation on</p>
        <ul>
          <li class="facebook"><a href="#" id="share-facebook"><i class="fa fa-facebook-square"></i> Facebook</a></li>
          <li class="twitter"><a href="https://twitter.com/intent/tweet?text=Hello%20world"><i class="fa fa-twitter-square"></i> Twitter</a></li>
          <li class="line"><a href="#"><i class="fontello icon-line"></i> LINE</a></li>
        </ul>
      </div>

      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <div class="contact-us">
            <p>If you want to know more about our donation systems,<br/>please contact us.</p>
            <div class="button"><a class="btn btn-primary">Contact us</a></div>
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>

    </div>
    <div class="col-lg-2 col-md-1"></div>
  </div>
</div>
{% endblock %}

{% block javascript %}
<script>
document.getElementById('share-facebook').onclick = function() {
  FB.ui({
    method: 'share',
    display: 'popup',
    href: '{{ WEBSITE_URL }}{{ request.path }}',
  }, function(response){});

  return false;
}


</script>
{% endblock %}